server:
  port: 8040
spring:   
  application:
    name: demo-cloud-zuul
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka 
    instance:
      prefer-ip-address: true
management:
  securtty:
         enabled: false
  endpoints:
    web:
      exposure:
        include: "*"
        
   
             
             
             
             
             
             